name: Update Docker
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1,15 * *'
jobs:
  build_test_and_push_images:
    name: Build Docker image test and deploy to DockerHub (latest, with chrome version)
    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Build docker image
        run: docker build -q -t profiq/node-java-chrome-ff .
      - name: Start docker image
        run: docker run -itd --name node-java-chrome-ff profiq/node-java-chrome-ff
      - name: Run tests
        run: docker exec node-java-chrome-ff ./tests.sh
      - name: Get latest chrome version
        run: echo "CHROME_VERSION=$(google-chrome --version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 | sed '/Google Chrome /s///')" >> $GITHUB_ENV
      - name: Tag with chrome version
        run: docker tag profiq/node-java-chrome-ff profiq/node-java-chrome-ff:chrome-${{ env.CHROME_VERSION }}
      - name: Get latest firefox version
        run: echo "FIREFOX_VERSION=$(firefox --version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 | sed '/Mozilla Firefox /s///')" >> $GITHUB_ENV
      - name: Tag with firefox version
        run: docker tag profiq/node-java-chrome-ff profiq/node-java-chrome-ff:firefox-${{ env.FIREFOX_VERSION }}
      - name: Tag with chrome and firefox version
        run: docker tag profiq/node-java-chrome-ff profiq/node-java-chrome-ff:ch${{ env.CHROME_VERSION }}-ff${{ env.FIREFOX_VERSION }}
      - name: Tag with latest
        run: docker tag profiq/node-java-chrome-ff profiq/node-java-chrome-ff:latest
      - name: Push to DockerHub
        run: docker push profiq/node-java-chrome-ff --all-tags
